-- Trigger tb_usuario 
DELIMITER $$
CREATE TRIGGER `I_Usuario` AFTER INSERT ON `tb_usuario`
 FOR EACH ROW BEGIN
  INSERT INTO tb_Log (tabela, codigo, operacao, campo, valor_antigo, valor_novo, data_modificacao, modificado_por )
  VALUES
      ('tb_Usuario', NEW.codigo, 'INSERT', 'perfil', '', NEW.perfil, NOW(), NEW.modificado_por),
      ('tb_Usuario', NEW.codigo, 'INSERT', 'nome', '', NEW.nome, NOW(), NEW.modificado_por),
      ('tb_Usuario', NEW.codigo, 'INSERT', 'email', '', NEW.email, NOW(), NEW.modificado_por),
      ('tb_Usuario', NEW.codigo, 'INSERT', 'senha', '', NEW.senha, NOW(), NEW.modificado_por),
      ('tb_Usuario', NEW.codigo, 'INSERT', 'suspenso', '', NEW.suspenso, NOW(), NEW.modificado_por),
      ('tb_Usuario', NEW.codigo, 'INSERT', 'foto', '', NEW.foto, NOW(), NEW.modificado_por);

   IF (NEW.perfil = 1) THEN -- administrador
    INSERT INTO tb_PermissaoUsuario (usuario, modulo, permissao, ativo)
     VALUES
         (NEW.codigo, 1, 1 ,1),
         (NEW.codigo, 1, 2, 1),
         (NEW.codigo, 1, 3, 1),
         (NEW.codigo, 1, 4, 1),
         (NEW.codigo, 2, 1, 0),
         (NEW.codigo, 2, 2, 0),
         (NEW.codigo, 2, 3, 0),
         (NEW.codigo, 2, 4, 0),
         (NEW.codigo, 3, 1, 0),
         (NEW.codigo, 3, 2, 0),
         (NEW.codigo, 3, 3, 0),
         (NEW.codigo, 3, 4, 0),
         (NEW.codigo, 4, 1, 1),
         (NEW.codigo, 4, 2, 1),
         (NEW.codigo, 4, 3, 1),
         (NEW.codigo, 4, 4, 1),
         (NEW.codigo, 5, 1, 0),
         (NEW.codigo, 5, 2, 0),
         (NEW.codigo, 5, 3, 0),
         (NEW.codigo, 5, 4, 0),
         (NEW.codigo, 6, 1, 0),
         (NEW.codigo, 6, 2, 0),
         (NEW.codigo, 6, 3, 0),
         (NEW.codigo, 6, 4, 0),
         (NEW.codigo, 7, 1, 0),
         (NEW.codigo, 7, 2, 0),
         (NEW.codigo, 7, 3, 0),
         (NEW.codigo, 7, 4, 0),
         (NEW.codigo, 8, 1, 0),
         (NEW.codigo, 8, 2, 0),
         (NEW.codigo, 8, 3, 0),
         (NEW.codigo, 8, 4, 0),
         (NEW.codigo, 9, 1, 1),
         (NEW.codigo, 9, 2, 1),
         (NEW.codigo, 9, 3, 1),
         (NEW.codigo, 9, 4, 1),
         (NEW.codigo, 10,1, 1),
         (NEW.codigo, 10,2, 1),
         (NEW.codigo, 10,3, 1),
         (NEW.codigo, 10,4, 1),
		 (NEW.codigo, 11,1, 1),
         (NEW.codigo, 11,2, 0),
         (NEW.codigo, 11,3, 1),
       	 (NEW.codigo, 11,4, 1),
		 (NEW.codigo, 12,1, 1),
		 (NEW.codigo, 12,2, 1),
 		 (NEW.codigo, 12,3, 1),
   		 (NEW.codigo, 12,4, 1),
		 (NEW.codigo, 13,1, 1),
		 (NEW.codigo, 13,2, 1),
		 (NEW.codigo, 13,3, 1),
		 (NEW.codigo, 13,4, 1),
		 (NEW.codigo, 14,1, 1),
		 (NEW.codigo, 14,2, 1),
		 (NEW.codigo, 14,3, 1),
		 (NEW.codigo, 14,4, 1),
		 (NEW.codigo, 15,1, 0),
		 (NEW.codigo, 15,2, 0),
		 (NEW.codigo, 15,3, 1),
		 (NEW.codigo, 15,4, 0);
   END IF;

   IF (NEW.perfil = 2) THEN -- profissional da saúde
    INSERT INTO tb_PermissaoUsuario (usuario, modulo, permissao, ativo)
      VALUES
         (NEW.codigo, 1, 1, 0),
         (NEW.codigo, 1, 2, 0),
         (NEW.codigo, 1, 3, 0),
         (NEW.codigo, 1, 4, 0),
         (NEW.codigo, 2, 1, 1),
         (NEW.codigo, 2, 2, 1),
         (NEW.codigo, 2, 3, 1),
         (NEW.codigo, 2, 4, 1),
         (NEW.codigo, 3, 1, 1),
         (NEW.codigo, 3, 2, 1),
         (NEW.codigo, 3, 3, 1),
         (NEW.codigo, 3, 4, 1),
         (NEW.codigo, 4, 1, 1),
         (NEW.codigo, 4, 2, 1),
         (NEW.codigo, 4, 3, 1),
         (NEW.codigo, 4, 4, 1),
         (NEW.codigo, 5, 1, 1),
         (NEW.codigo, 5, 2, 1),
         (NEW.codigo, 5, 3, 1),
         (NEW.codigo, 5, 4, 1),
         (NEW.codigo, 6, 1, 1),
         (NEW.codigo, 6, 2, 1),
         (NEW.codigo, 6, 3, 1),
         (NEW.codigo, 6, 4, 1),
         (NEW.codigo, 7, 1, 1),
         (NEW.codigo, 7, 2, 1),
         (NEW.codigo, 7, 3, 1),
         (NEW.codigo, 7, 4, 1),
         (NEW.codigo, 8, 1, 1),
         (NEW.codigo, 8, 2, 1),
         (NEW.codigo, 8, 3, 1),
         (NEW.codigo, 8, 4, 1),
         (NEW.codigo, 9, 1, 0),
         (NEW.codigo, 9, 2, 1),
         (NEW.codigo, 9, 3, 1),
         (NEW.codigo, 9, 4, 0),
         (NEW.codigo, 10, 1, 1),
         (NEW.codigo, 10, 2, 1),
         (NEW.codigo, 10, 3, 1),
         (NEW.codigo, 10, 4, 1),
         (NEW.codigo, 11, 1, 0),
		 (NEW.codigo, 11 ,2 ,0),
		 (NEW.codigo, 11, 3, 0),
		 (NEW.codigo, 11, 4, 0),
		 (NEW.codigo, 12, 1, 0),
		 (NEW.codigo, 12, 2, 0),
		 (NEW.codigo, 12, 3, 0),
		 (NEW.codigo, 12, 4, 0),
		 (NEW.codigo, 13, 1, 0),
		 (NEW.codigo, 13, 2, 0),
		 (NEW.codigo, 13, 3, 0),
		 (NEW.codigo, 13, 4, 0),
		 (NEW.codigo, 14, 1, 0),
		 (NEW.codigo, 14, 2, 0),
		 (NEW.codigo, 14 ,3, 0),
		 (NEW.codigo, 14 ,4 ,0),
		 (NEW.codigo, 15, 1, 0),
		 (NEW.codigo, 15, 2, 0),
		 (NEW.codigo, 15 ,3, 0),
		 (NEW.codigo, 15 ,4 ,0);

   END IF;
	
    IF (NEW.perfil = 6) THEN -- representante
    INSERT INTO tb_PermissaoUsuario (usuario, modulo, permissao, ativo)
     VALUES
         (NEW.codigo, 1, 1 ,0),
         (NEW.codigo, 1, 2, 0),
         (NEW.codigo, 1, 3, 0),
         (NEW.codigo, 1, 4, 0),
         (NEW.codigo, 2, 1, 0),
         (NEW.codigo, 2, 2, 0),
         (NEW.codigo, 2, 3, 0),
         (NEW.codigo, 2, 4, 0),
         (NEW.codigo, 3, 1, 0),
         (NEW.codigo, 3, 2, 0),
         (NEW.codigo, 3, 3, 0),
         (NEW.codigo, 3, 4, 0),
         (NEW.codigo, 4, 1, 0),
         (NEW.codigo, 4, 2, 0),
         (NEW.codigo, 4, 3, 0),
         (NEW.codigo, 4, 4, 0),
         (NEW.codigo, 5, 1, 0),
         (NEW.codigo, 5, 2, 0),
         (NEW.codigo, 5, 3, 0),
         (NEW.codigo, 5, 4, 0),
         (NEW.codigo, 6, 1, 0), -- configuração
         (NEW.codigo, 6, 2, 0),
         (NEW.codigo, 6, 3, 0),
         (NEW.codigo, 6, 4, 0),
         (NEW.codigo, 7, 1, 0),
         (NEW.codigo, 7, 2, 0),
         (NEW.codigo, 7, 3, 0),
         (NEW.codigo, 7, 4, 0),
         (NEW.codigo, 8, 1, 0),
         (NEW.codigo, 8, 2, 0),
         (NEW.codigo, 8, 3, 0),
         (NEW.codigo, 8, 4, 0),
         (NEW.codigo, 9, 1, 0),
         (NEW.codigo, 9, 2, 0),
         (NEW.codigo, 9, 3, 0),
         (NEW.codigo, 9, 4, 0),
         (NEW.codigo, 10, 1,0),
         (NEW.codigo, 10, 2,0),
         (NEW.codigo, 10, 3,0),
         (NEW.codigo, 10, 4,0),
         (NEW.codigo, 11, 1,0), -- voucher
		 (NEW.codigo, 11 ,2,0),
		 (NEW.codigo, 11, 3,1),
		 (NEW.codigo, 11, 4,0),
		 (NEW.codigo, 12, 1,0),-- representante
		 (NEW.codigo, 12, 2,1),
		 (NEW.codigo, 12, 3,1),
		 (NEW.codigo, 12, 4,0),
		 (NEW.codigo, 13, 1,1), -- contato
		 (NEW.codigo, 13, 2,1),
		 (NEW.codigo, 13, 3,1),
		 (NEW.codigo, 13, 4,1),
		 (NEW.codigo, 14, 1,0), -- serviço
		 (NEW.codigo, 14, 2,0),
		 (NEW.codigo, 14 ,3,0),
		 (NEW.codigo, 14 ,4,0),
		 (NEW.codigo, 15, 1,0), -- pacote
		 (NEW.codigo, 15, 2,0),
		 (NEW.codigo, 15 ,3,0),
		 (NEW.codigo, 15 ,4,0);
         
   END IF;
END
$$
DELIMITER ;